const strings = {
  accountVerified: 'Account verified',
  amazon: 'Amazon',
  appName: 'FurniBAZAR',
  attemptAgain: 'Attempt again',
  continue: 'CONTINUE',
  continueWithGoogle: 'Continue with Google',
  enterMobileNumber: 'Enter mobile number',
  errorNotification: 'Error Notification',
  enterPassword: 'Enter password',
  error: 'error',
  faceBook: 'Facebook',
  greaterThanTenDigitsError: 'Mobile number is exceeding 10 digits',
  haventRecievedOtp: "Haven't recieved the OTP?",
  letsStart: "LET'S START",
  loginInsrtuctionLine: 'Enter your credentials to Login',
  loginScreenErrorDescription:
    'Please enter the credential details. If not create an account to proceed ahead.',
  mobile: 'Mobile',
  orLoginWith: 'Or login with',
  otpScreenText: 'Enter the OTP that you have recieved',
  otpTimerText: 'This OTP is valid for {0} seconds',
  password: 'Password',
  resendOtp: 'Resend OTP',
  success: 'success',
  successOtpDescription: 'Successfully logged in!',
  tagLine: 'We provide quality products just for you',
  tenDigitsErrorMessage: 'Mobile number needs to have 10 digits',
  twitter: 'Twitter',
  username: 'Username',
  validPassword: 'Enter valid password',
  validUsername: 'Enter valid username',
  validMobileNumber: 'Enter valid mobile number',
  verify: 'VERIFY',
  wrongOtpDescription: 'Wrong OTP entered. Please try again.',
};
export default strings;
