const testID = {
  appHeader: 'appHeader',
  bottomTabIconNonSelected: 'bottomTabIconNonSelected',
  bottomTabIconOnPress: 'bottomTabIconOnPress',
  bottomTabIconSelected: 'bottomTabIconSelected',
  bottomTabIconText: 'bottomTabIconText',
  buttonContainer: 'buttonContainer',
  buttonView: 'buttonView',
  buttonText: 'buttonText',
  categoryIcon: 'categoryIcon',
  carousalSlider: {
    view: 'carousalSlider',
    header: 'carousalSliderHeader',
    image: 'carousalSliderImage',
    description: 'carousalSliderDescription',
    discountView: 'carousalSliderDiscountView',
    discountValue: 'carousalSliderDiscountValue',
  },
  filterIcon: 'filterIcon',
  filterModalComponent: 'filterModalComponent',
  filterModal: {
    apply: 'apply',
    clearbutton: 'filterModalViewClearbutton',
    cleartext: 'filterModalViewClearText',
    close: 'close',
    companySearch: 'companySearch',
    companySearchInput: 'companySearchInput',
    crossIcon: 'crossIcon',
    crossIconButton: 'crossIconButton',
    filteredCategoryIcon: 'FMFilteredCategoryIcon',
    filteredCategoryText: 'FMFilteredCategoryText',
    rating1: 'rating1',
    rating2: 'rating2',
    rating3: 'rating3',
    rating4: 'rating4',
    rating5: 'rating5',
    selectedCategoryText: 'FMSelectedCategoryText',
    selectedCompanies: 'selectedCompanies',
    selectedCompanyNames: 'selectedCompanyNames',
    selectedCompaniesView: 'FMSelectedCompaniesView',
    slider: 'slider',
    text: 'filterModalText',
    view: 'filterModalView',
  },
  pagination: {
    nonSelectedDot: 'nonSelectedDot',
    selectedDot: 'selectedDot',
    selectedDotText: 'selectedDotText',
    view: 'paginationView',
  },
  productFilterIcon: 'productFilterIcon',
  saveIcon: 'saveIcon',
  searchIcon: 'searchIcon',
  shortButton: 'shortButton',
  shortButtonView: 'shortButtonView',
  shortButtonText: 'shortButtonText',
  shortButtonImage: 'shortButtonImage',
  slider: {
    view: 'sliderView',
    line: 'sliderLine',
    dot: 'sliderDot',
  },
  starIcon: 'starIcon',
  tagIcon: 'tagIcon',
  toastCloseButton: 'toastCloseButton',
  toastCloseButtonPress: 'toastCloseButtonPress',
  toastDescription: 'toastDescription',
  toastIcon: 'toastIcon',
  toastTitle: 'toastTitle',
};
export default testID;
