const testID = {
  appHeader: 'appHeader',
  bottomTabIconNonSelected: 'bottomTabIconNonSelected',
  bottomTabIconOnPress: 'bottomTabIconOnPress',
  bottomTabIconSelected: 'bottomTabIconSelected',
  bottomTabIconText: 'bottomTabIconText',
  buttonContainer: 'buttonContainer',
  buttonView: 'buttonView',
  buttonText: 'buttonText',
  categoryIcon: 'categoryIcon',
  filterIcon: 'filterIcon',
  filteredCategoryIcon: 'filteredCategoryIcon',
  pagination: {
    nonSelectedDot: 'nonSelectedDot',
    selectedDot: 'selectedDot',
    selectedDotText: 'selectedDotText',
    view: 'paginationView',
  },
  productFilterIcon: 'productFilterIcon',
  saveIcon: 'saveIcon',
  searchIcon: 'searchIcon',
  shortButton: 'shortButton',
  shortButtonView: 'shortButtonView',
  shortButtonText: 'shortButtonText',
  shortButtonImage: 'shortButtonImage',
  slider: {
    view: 'sliderView',
    line: 'sliderLine',
    dot: 'sliderDot',
  },
  starIcon: 'starIcon',
  tagIcon: 'tagIcon',
  toastCloseButton: 'toastCloseButton',
  toastCloseButtonPress: 'toastCloseButtonPress',
  toastDescription: 'toastDescription',
  toastIcon: 'toastIcon',
  toastTitle: 'toastTitle',
};
export default testID;
