const testID = {
  appHeader: 'appHeader',
  bottomTabIconNonSelected: 'bottomTabIconNonSelected',
  bottomTabIconOnPress: 'bottomTabIconOnPress',
  bottomTabIconSelected: 'bottomTabIconSelected',
  bottomTabIconText: 'bottomTabIconText',
  buttonContainer: 'buttonContainer',
  buttonView: 'buttonView',
  buttonText: 'buttonText',
  shortButton: 'shortButton',
  shortButtonView: 'shortButtonView',
  shortButtonText: 'shortButtonText',
  shortButtonImage: 'shortButtonImage',
  toastCloseButton: 'toastCloseButton',
  toastCloseButtonPress: 'toastCloseButtonPress',
  toastDescription: 'toastDescription',
  toastIcon: 'toastIcon',
  toastTitle: 'toastTitle',
};
export default testID;
